name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - use: actions/checkout@v2
      - name: use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: npm ci
      - run: npm run format:check
        env:
          CI: true
